apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
spec:
  rules:
  - host: ec2-18-209-161-12.compute-1.amazonaws.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 80
      - path: /api/service1
        backend: 
          serviceName: service1
          servicePort: 5000
      - path: /api/service2
        backend: 
          serviceName: service2
          servicePort: 5000
