apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: service1
  name: service1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: service1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: service1
    spec:
      containers:
      - image: gregigs/igs-service1
        name: igs-service1
        resources: {}
