apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: service1-ingress
  annotations:
spec:
  rules:
  - host: localhost 
    http:
      paths:
      - path: /api/service1/*
        backend:
          serviceName: service1
          servicePort: 5004
