apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service3
  name: service3
spec:
  type: ClusterIP 
  ports:
  - port: 5000 
    protocol: TCP
    targetPort: 5000 
  selector:
    app: service3
status:
  loadBalancer: {}
