apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: service2-ingress
  annotations:
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /api/service2/*
        backend:
          serviceName: service2
          servicePort: 5005
