apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: service2
  name: service2
spec:
  type: ClusterIP 
  ports:
  - port: 5000 
    protocol: TCP
    targetPort: 5000 
  selector:
    app: service2
status:
  loadBalancer: {}
